[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.contracts_dino_clar]
path = 'contracts/contracts_dino_clar.clar'
clarity_version = 3
epoch = 3.0

[contracts.contracts_ttt_clar]
path = 'contracts/contracts_ttt_clar.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
